apiVersion: v1
kind: Service
metadata:
  name: capital-gains-service
  namespace: stocks-system
spec:
  selector:
    app: capital-gains
  ports:
  - protocol: TCP
    port: 8080   # External port the service exposes
    targetPort: 8080   # Port your application is running on (container port)
  type: ClusterIP