apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 1Gi

  accessModes:
    - ReadWriteOnce

  storageClassName: standard

  persistentVolumeReclaimPolicy: Retain

  hostPath:
    path: /data/mongo
    type: DirectoryOrCreate
