apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: stocks-system
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/mongo


apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: stocks-system
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: /data/mongo